### ISSUE TITLE
Cordova 6.0.0 always builds as an emulator for iOS

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-cordova-tasks#28]
Something has changed in 6.0.0 that is breaking how we are passing in arguments to iOS.  The default for the build task is supposed to default to device but for some reason is defaulting to emulator.

**Comment by ryuyu** [comment]
The changes to the argument parsing that was made in 5.4.x were reverted in 6.0.0. Taco team build is being updated to account for this.
