### ISSUE TITLE
Cordova 6.0.0 Android build on Linux/OSX fails

### ISSUE THREAD

**Issue by ryuyu** [Microsoft/vsts-cordova-tasks#30]
For some reason, the build on Cordova 6.0.0 on linux and osx fails with the following message:
Task '"--no-daemon"' not found in root project 'android'.

This does not occur when building against windows.

Currently in discussion with Cordova team.

**Comment by Chuxel** [comment]
This appears to be a bug in Cordova 6.0.0. A patch is being submitted for an update.

**Comment by ryuyu** [comment]
This has been address in Cordova 6.1.x.
Closing.
