### ISSUE TITLE
Ionic: spawn EACCES error when JavaScript file is present in the hooks folder without the execute bit set (iOS, OSX, Linux)

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-cordova-tasks#36]
If you check in a "shell" based hook into source control like 010_add_platform_class.js found in hooks/after_prepare from Windows it typically won't have an execute bit set [as required by Cordova](http://cordova.apache.org/docs/en/latest/guide/appdev/hooks/index.html).

The **workaround** is actually quite simple.  Either add the exectue bit to this file in source control or add a Command Line task to execute the following:

chmod +x hooks/after_prepare/010_add_platform_class.js

...or something similar.

However, unfortunately Ionic's use of hook file makes this problem fairly common. We should trap spawn EACCES errors and output a message using this specific example as a common reason along with the workaround to use the VSTS Command Line task.

**Comment by Chuxel** [comment]
More details: The VS remotebuild agent sets execute bits here on behalf of the user. Given I expect this will be quite common we should follow suit in this extension and taco-team-build.

**Comment by ryuyu** [comment]
Fixed in latest release of Cordova Task Extension (1.2.2)
