### ISSUE TITLE
Downloading Cordova fails if the CORDOVA_CACHE folder does not exist on Windows

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-cordova-tasks#38]
Due to what appears to be a bug in Node.js, the code in taco-team-build is not properly creating the cordova cache folder (%APPDATA%\taco_home\node_modules) if it does not exist.

The workaround is to simply create the folder.  This problem is limited to local Windows agents does not exist in the VSTS hosted pool.

**Comment by ryuyu** [comment]
Fixed in latest release of Cordova Task Extension (1.2.2)
