### ISSUE TITLE
Add ability to set application id, name and version in config.xml in CordovaBuild

### ISSUE THREAD

**Issue by mcm-ham** [Microsoft/vsts-cordova-tasks#40]
We would like to be able to have a different application name and id between our staging and release builds, and would like to be able to set the version for each release. Here is an existing script that shows how this can be done:

https://github.com/dpogue/seymour/blob/master/src/seymour.js

**Comment by Chuxel** [comment]
Thanks for the feedback!  I'd like to understand a bit more about the scenario you're trying to execute.  Where would you expect to see the version number set?  Is this something you would set in the build definition?  Or are you looking to automatically increase the version number for each build?

**Comment by mcm-ham** [comment]
So currently we have an ember app which we build in the build step and then test. Then in the release step we're looking at building the cordova app for ios, android, windows and web deploy to web. We'll be automatically triggering the release of the staging app after each checkin, and manually trigger the release of the production app.

I was thinking it can just be a textbox in the cordova build properties. For our staging app we're interested in an increasing version number but don't care about the format so would probably just use the build number `$(Build.BuildNumber)` or release number `$(rev:r)` into the version textbox (or maybe something like `$(productionVersion).$(Build.BuildNumber)`), and for the release build we'd probably change it manually for each release using a custom variable `$(productionVersion)`.

**Comment by Chuxel** [comment]
Thanks - Appreciate the feedback. This is absolutely something that we have indeed been thinking about. Generally we find environment specific config is a problem for Cordova. There are actually similar issues with services like CodePush where you want difference preference values depending on whether you're building a staging or production version of the app. We will add this to our backlog to think about a good solution.

@lostintangent FYI

**Comment by slorber** [comment]
hey @mcm-ham is it possible that you write a bit more in a gist about how you manage multiple environments (staging/production) with your cordova app? I'm particularly interested to know how you distribute that staging app to the app testers.


I don't use VSTS but I probably have the same usecase and I need to override config.xml values per env (including app id, CodePush/Intercom/Apns/Gcm keys...)

**Comment by Chuxel** [comment]
@slorber You may find this blog post on the topic useful: http://www.ryanjsalva.com/2016/05/07/maintaining-different-release-configurations.html

**Comment by slorber** [comment]
thanks @Chuxel 

Actually I was more interested on how to distribute a staging / production binary to the stores rather than how to setup gulp/git/CI :) 

I'm not using VSTS but I just installed CodePush and it works very fine. I splitted my userbase to Staging=team members / Production=all others, and we can now deploy for my team first and then for all users. This is a great progress for beta-testing against a production backend, but what I really wanted to know is how I am supposed to manage 2 apps where one run against a production backend and the other against a staging backend :)

**Comment by drewgillies** [comment]
As there hasn't been any movement on this for nearly a Year, I'll go ahead and close it. Please let me know if you have any concerns with this.

**Comment by markaschneider** [comment]
+1 for the feature request
