### ISSUE TITLE
vsts not showing "queue" in the dropdown whille trying to queue new build

### ISSUE THREAD

**Issue by sowsan** [Microsoft/vsts-cordova-tasks#46]
Hello,

I'm trying all the steps mentioned to create a build definition for cordova. While testing a build queue new build option is not showing any queues in the drop down to select. Any idea ?

Regards,
Sowmyan

**Comment by Chuxel** [comment]
Strange - That is not something anything related to Cordova should affect.  By default there normally is a "Hosted" and "default" queue associated with your account.  Are you certain you have permissions set to allow you to use the queues?  (If you own the instance you should, but if you are a participant your administrator may not have given you access.)

**Comment by Chuxel** [comment]
Closing due to lack of response.
