### ISSUE TITLE
Cordova Command fail with 'Arguments to path.join must be strings'

### ISSUE THREAD

**Issue by akamud** [Microsoft/vsts-cordova-tasks#54]
When I run `cordova rm android` on my agent (on-premises) I get this error:

```
path.js:233
throw new TypeError('Arguments to path.join must be strings');
TypeError: Arguments to path.join must be strings
at Object.win32.join (path.js:233:13)
at Object.<anonymous> (C:\agent\tasks\CordovaCommand\1.3.9\lib\node-manager.js:20:114)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (C:\agent\tasks\CordovaCommand\1.3.9\lib\node-setup.js:10:19)
at Module._compile (module.js:460:26)
```

I noticed it was a problem getting the paths [here](https://github.com/Microsoft/vsts-cordova-tasks/blob/master/lib/node-manager.js#L20), so I printed all the paths it is trying to access during the task, and noticed all of them are undefined:

```
NODE_VERSION_CACHE undefined
APPDATA undefined
HOME undefined
```

Could this be a bug in the task?

Versions used:
CordovaCommand: `1.3.9`
Cordova: `5.4.0`

**Comment by BretJohnson** [comment]
@akamud - Can you say how the VSTS agent is deployed here--is it running as a service?

**Comment by akamud** [comment]
We are running it via command line at the moment.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.4.14&pv=8.3&source=email_footer_2]
On qua, jul 6, 2016 at 4:02 PM, Bret Johnson <notifications@github.com> wrote:
@akamud [https://github.com/akamud] - Can you say how the VSTS agent is deployed here--is it running as a service?

**Comment by BretJohnson** [comment]
Thanks.   Can you also do **echo %APPDATA%** from the command prompt (the same one where you run the agent) to verify APPDATA is actually set.  Also, what the exact version of Windows that you're on?  It seems like this is earlier a configuration problem or a bug with the newest Windows task agent.

**Comment by BretJohnson** [comment]
@akamud - Also, can you please say what version of the agent is installed.  In particular, is it the "Windows" agent or the new "Windows (preview)" agent (the cross platform one).  And knowing the version number would be great too.

**Comment by jicongw** [comment]
@akamud Thanks for reporting this issue. I was investigating this issue and looks like we do not have enough information. Can you please respond with information about running ` echo %APPDATA%` on the agent ? Looks like that may not be defined.

**Comment by akamud** [comment]
Sorry for taking so long to respond, I was getting this error in a project from another team at my company, unfortunately I was trying to get them to send me more information with no success.

I'm sorry for leaving this with incomplete information.

**Comment by jicongw** [comment]
@akamud No worries. Let's close this issue. If you found the necessary information, please reopen. Thanks :)
