### ISSUE TITLE
Code Signing Fails after Xcode 8 and OS X Sierra update

### ISSUE THREAD

**Issue by bradwyoung** [Microsoft/vsts-cordova-tasks#58]
I have had automated builds of my cordova project working for several months but two weeks ago my Mac that I am using as the build agent installed an update to Xcode and the builds started failing with the following error.

No certificate matching 'iPhone Distribution: *****(******)' for team '******': Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.

I have the certificate and provisioning profile files in the source repository encrypted per the following article.  I also revoked and created a new certificate and provisioning profile.
https://www.visualstudio.com/en-us/docs/build/apps/mobile/secure-certs

The only solution I have found is to remove all of the override settings for signing under iOS of the Corodva build task.  Then add a build.json file like outlined in the following article.

https://dpogue.ca/articles/cordova-xcode8.html

This does work on a mac that I personally own and can log into Xcode and setup a developer account but it does not work on a MacInCloud VSTS build agent.

**Comment by bradwyoung** [comment]
It has almost been a month since I reported this issue and not even one comment, So, I guess I am the only person that has seen this issue?  I would like to return to my original build configuration so I could move my builds to MacInClound VSTS build agent.

**Comment by johnwargo** [comment]
Right now, the solution you have is the only workaround and we updated our docs a while back to reference this at https://taco.visualstudio.com/en-us/docs/vs-taco-2017-ios-guide/#xcode8.

**Comment by bradwyoung** [comment]
I would recommend adding something here on the GitHub landing page because the getting started links take you to the articles that I followed to setup my builds and I did not see that information on them.  

Thank you for the reply and confirming the issue.

**Comment by jicongw** [comment]
Hi @bradwyoung , I have published a new version of [vsts-cordova-tasks](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.cordova-extension
) in VSTS extension marketplace. It will supply appropriate error messages in the log console.
Thanks for reporting the issue!
