### ISSUE TITLE
CordovaError: Platform ios already added

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vsts-cordova-tasks#59]
Hi Folks,

I created an SO question yesterday due to a build failure, didn't realize you all had a GIT repo. It is described here.

http://stackoverflow.com/questions/41030755/cordovaerror-platform-ios-already-added

Please note; I have Platforms in my working directory but I do not have Platforms in my source control branch.

Thanks
Jordan

**Comment by MSLaguana** [comment]
I've had a look at this, and I'm a bit confused how it could happen. I believe the error is happening when we execute the line at https://github.com/Microsoft/taco-team-build/blob/master/taco-team-build.js#L227 but that line should only be executed after we've checked for the platform and not found it.

You mentioned that you are running the agent in interactive mode; are you running the agent from within (perhaps multiple folders down) a cordova project?

**Comment by jrmcdona** [comment]
My repo looks like this.  I am building myApp which is a test app to get buiild working.
![screen shot 2016-12-08 at 2 06 21 pm](https://cloud.githubusercontent.com/assets/4327773/21025835/9aff1ce0-bd4f-11e6-8a98-068b0b5d9dd4.png)

**Comment by jrmcdona** [comment]
Here is my agent.  Not sure what you mean by running deep in a cordova project.  The agent was installed separately in a different folder.

![screen shot 2016-12-08 at 2 06 21 pm](https://cloud.githubusercontent.com/assets/4327773/21028367/5c5a7fe2-bd5a-11e6-8b26-b9e4ea8653f3.png)

**Comment by MSLaguana** [comment]
It looks like you've uploaded the same picture twice, but I was wondering whether you had run the agent from a folder `/some/path/to/a/folder/` where a parent such as `/some/path/` was a cordova project with a `config.xml` and a `platforms` folder.

If that was the case, then cordova can get confused about the project it is operating on, and that may have caused this kind of issue.

**Comment by jrmcdona** [comment]
I updated my answer and fixed the pick, but looks like not in time.  But if you refresh it may be helpful.

**Comment by MSLaguana** [comment]
Just to be sure: what folder were you in when you ran `./run.sh`? And if you run `cordova info` in that same location does it print out a bunch of information, or an error stating that the current folder is not a cordova project?

**Comment by jrmcdona** [comment]
Well maybe this is the issue!  I was in my iosagent folder.   Do I need to run the /run sh from the "myApp" folder for this to work right?

Jordans-Mac-mini:iosagent jordanmc$ cordova info
Error: Current working directory is not a Cordova-based project.
Jordans-Mac-mini:iosagent jordanmc$

**Comment by MSLaguana** [comment]
No, you need to make sure that it does _not_ run from inside there, I just wanted to make sure that you weren't; the error from `cordova info` is exactly what you want to see there to make sure that when the agent runs cordova commands it must be working from inside your project, not some other one it happened to find.

**Comment by jrmcdona** [comment]
Here is what i get when I run _cordova info_ from my project:

Jordans-Mac-mini:myApp jordanmc$ cordova info
Collecting Data...


Node version: v6.6.0

Cordova version: 6.4.0

Config.xml file: 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="com.ionicframework.myapp354717" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>myApp</name>
  <description>
        An Ionic Framework and Cordova project.
    </description>
  <author email="you@example.com" href="http://example.com/">
      Your Name Here
    </author>
  <content src="index.html"/>
  <access origin="*"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="SplashScreenDelay" value="2000"/>
  <preference name="FadeSplashScreenDuration" value="2000"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashScreen" value="screen"/>
  <feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" onload="true"/>
  </feature>
  <platform name="ios">
    <icon src="resources/ios/icon/icon.png" width="57" height="57"/>
    <icon src="resources/ios/icon/icon@2x.png" width="114" height="114"/>
    <icon src="resources/ios/icon/icon-40.png" width="40" height="40"/>
    <icon src="resources/ios/icon/icon-40@2x.png" width="80" height="80"/>
    <icon src="resources/ios/icon/icon-40@3x.png" width="120" height="120"/>
    <icon src="resources/ios/icon/icon-50.png" width="50" height="50"/>
    <icon src="resources/ios/icon/icon-50@2x.png" width="100" height="100"/>
    <icon src="resources/ios/icon/icon-60.png" width="60" height="60"/>
    <icon src="resources/ios/icon/icon-60@2x.png" width="120" height="120"/>
    <icon src="resources/ios/icon/icon-60@3x.png" width="180" height="180"/>
    <icon src="resources/ios/icon/icon-72.png" width="72" height="72"/>
    <icon src="resources/ios/icon/icon-72@2x.png" width="144" height="144"/>
    <icon src="resources/ios/icon/icon-76.png" width="76" height="76"/>
    <icon src="resources/ios/icon/icon-76@2x.png" width="152" height="152"/>
    <icon src="resources/ios/icon/icon-83.5@2x.png" width="167" height="167"/>
    <icon src="resources/ios/icon/icon-small.png" width="29" height="29"/>
    <icon src="resources/ios/icon/icon-small@2x.png" width="58" height="58"/>
    <icon src="resources/ios/icon/icon-small@3x.png" width="87" height="87"/>
    <splash src="resources/ios/splash/Default-568h@2x~iphone.png" height="1136" width="640"/>
    <splash src="resources/ios/splash/Default-667h.png" height="1334" width="750"/>
    <splash src="resources/ios/splash/Default-736h.png" height="2208" width="1242"/>
    <splash src="resources/ios/splash/Default-Landscape-736h.png" height="1242" width="2208"/>
    <splash src="resources/ios/splash/Default-Landscape@2x~ipad.png" height="1536" width="2048"/>
    <splash src="resources/ios/splash/Default-Landscape@~ipadpro.png" height="2048" width="2732"/>
    <splash src="resources/ios/splash/Default-Landscape~ipad.png" height="768" width="1024"/>
    <splash src="resources/ios/splash/Default-Portrait@2x~ipad.png" height="2048" width="1536"/>
    <splash src="resources/ios/splash/Default-Portrait@~ipadpro.png" height="2732" width="2048"/>
    <splash src="resources/ios/splash/Default-Portrait~ipad.png" height="1024" width="768"/>
    <splash src="resources/ios/splash/Default@2x~iphone.png" height="960" width="640"/>
    <splash src="resources/ios/splash/Default~iphone.png" height="480" width="320"/>
  </platform>
</widget>

Plugins: 

cordova-plugin-console,cordova-plugin-device,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-vs-taco-support,cordova-plugin-whitelist,ionic-plugin-keyboard

iOS platform:

Xcode 8.0
Build version 8A218a

**Comment by MSLaguana** [comment]
Did you manually add `cordova-plugin-vs-taco-support` to your project? If not, that looks like you are pointing at the project that is operated on by VSTS, and it has the iOS platform installed (which would cause the error you're seeing).

**Comment by jrmcdona** [comment]
No I didn't add anything to myApp project.  The only thing I did on this project was run command "ionic start myApp tabs" just to get a blank app to get the build working.   

But yes,  myApp is what is connected to VSTS/GIT and myApp is my local working area and I push it to GIT.

When I was installing the ios agent it asked me for a "Work folder" .  This prompt was not in documentation either.    I supplied /Documents/repos/myApp to this Work folder. prompt.   The default was "_work" but I am not sure what this actually is doing and wasn't documented. 

It could/should have been in the Download and Configure section of this doc:
https://www.visualstudio.com/en-us/docs/build/admin/agents/v2-osx

Could that be an issue?

**Comment by MSLaguana** [comment]
I believe that is indeed your issue: The work folder is intended to be a folder that the VSTS agent can own and modify freely, so it should be an empty folder initially. Because you had pointed it at your local app folder, it was trying to modify that and confused itself.

Try reconfiguring the app and specifying a fresh folder for the Work folder, and see if that resolves the issue for you. I'll see if I can get the docs updated.

**Comment by jrmcdona** [comment]
Hi, updated things.  So this why I changed "_work" to my own working folder to begin with.  Here is the error.  Thanks for helping me through this.

Removing Xcconfig update hook
**{ CordovaError: Current working directory is not a Cordova-based project.
    at Object.cdProjectRoot** (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/cordova-lib/src/cordova/util.js:151:15)
    at /Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/cordova-lib/src/cordova/plugin.js:48:40
    at _fulfilled (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:749:13)
    at /Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:810:14
    at flush (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'CordovaError',
  message: 'Current working directory is not a Cordova-based project.',
  code: 0,
  context: undefined }
Task failed

**Comment by jrmcdona** [comment]
Hi,  Any other thoughts?

Thanks
