### ISSUE TITLE
Not specifying a configuration results in a failed build with strange error

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-cordova-tasks#6]
The code expects a configuration to be passed in and due to how we parse the configuration value results in a strange error.

![untitled](https://cloud.githubusercontent.com/assets/312252/11477270/12d6c69a-973c-11e5-907b-d45794469871.png)

This code is the issue.

    configuration = tasklibrary.getInput('configuration', /* required */ true).toLowerCase();
    buildArgs.push('--' + configuration);

A "--" by itself results in escaping of other args like "device" and this being passed directly to the platform which causes the above error.

If configuration is blank or invalid (not "debug" or "release") we should error stating it is a required value.

**Comment by ryuyu** [comment]
I submitted a pull request addressing this issue. Please take a look and let me know what you think.
https://github.com/Microsoft/vsts-cordova-tasks/pull/7

**Comment by ryuyu** [comment]
Pull request (https://github.com/Microsoft/vsts-cordova-tasks/pull/7) merged. Issue should be resolved.
