### ISSUE TITLE
Cordova plugins not being installed

### ISSUE THREAD

**Issue by bmwertman** [Microsoft/vsts-cordova-tasks#61]
I'm trying to move an existing ionic project over to VSTS CI and running into an issue with not being able to get my Cordova plugins to install. I've tried three different build configurations with varying results;

1) **Build steps - npm install, cordova build android[cordova v6.4.0] , hockeyapp deploy**
    Results summary: Builds and deploys to Hockeyapp successfully but no Cordova hooks appear to have ran and no plugins get installed.

2) **Build steps - npm install, ionic build android[cordova v6.4.0, ionic v2.0.0], hockeyapp deploy**
    Results summary: Builds and deploys to Hockeyapp successfully Cordova hooks do not appear to run but a partial list of Cordova plugins get installed, namely;
     - cordova-plugin-device 
     - cordova-plugin-console
     - cordova-plugin-whitelist
     - cordova-plugin-splashscreen (Default splash screen still gets ran instead of my custom one) 
     - cordova-plugin-statusbar
     - ionic-plugin-keyboard

    Missing plugins include; "cordova-plugin-console",
    -  cordova-plugin-contacts
    -  cordova-plugin-file
    -  cordova-plugin-file-transfer
    -  cordova-plugin-inappbrowser
    -  cordova-plugin-hockeyapp
    -  cordova-plugin-screen-orientation
    -  cordova-plugin-calendar 
    -  cordova-plugin-compat
    -  cordova-plugin-image-picker
    -  https://github.com/whiteoctober/cordova-plugin-app-version.git
    -  https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview
    -  https://github.com/bmwertman/phonegap-plugin-push/

3) **Build steps - npm install, ionic platform add android[cordova v6.4.0, ionic v2.0.0], ionic build android[cordova v6.4.0, ionic v2.0.0], hockeyapp deploy**
     Results summary: Builds and deploys to Hockeyapp successfully. Cordova hooks attempt to run but no Cordova plugins get installed. All plugin install hooks fail with an error similar to as follows;
```
Fetching plugin "cordova-plugin-whitelist@1.3.1" via npm
Installing "cordova-plugin-whitelist" for android
ANDROID_HOME=C:\java\androidsdk\android-sdk
JAVA_HOME=C:\java\jdk\jdk1.8.0_102
Subproject Path: CordovaLib
cp: dest file already exists: D:\a\1\s\platforms\android\gradlew.bat
shell.js: internal error
Error: ENOENT: no such file or directory, chmod 'D:\a\1\s\platforms\android\gradle\wrapper\gradle-wrapper.jar'
at Error (native)
at Object.fs.chmodSync (fs.js:1154:18)
at Object.chmodSync (C:\cordova\node_modules\cordova\6.4.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:220:19)
at copyFileSync (D:\a\1\s\platforms\android\cordova\node_modules\shelljs\src\cp.js:41:6)
at cpdirSyncRecursive (D:\a\1\s\platforms\android\cordova\node_modules\shelljs\src\cp.js:82:9)
at D:\a\1\s\platforms\android\cordova\node_modules\shelljs\src\cp.js:183:9
at Array.forEach (native)
at Object._cp (D:\a\1\s\platforms\android\cordova\node_modules\shelljs\src\cp.js:157:11)
at Object.cp (D:\a\1\s\platforms\android\cordova\node_modules\shelljs\src\common.js:186:23)
at D:\a\1\s\platforms\android\cordova\lib\builders\GradleBuilder.js:182:15
```

And the hook, `after_platform_add/010_install_plugins.js`, has the following script;
```
#!/usr/bin/env node

/**
 * Install all plugins listed in package.json
 * https://raw.githubusercontent.com/diegonetto/generator-ionic/master/templates/hooks/after_platform_add/install_plugins.js
 */
var exec = require('child_process').exec;
var sys = require('sys');

var packageJSON = null;

try {
  packageJSON = require('../../package.json');
} catch (ex) {
  console.log('\nThere was an error fetching your package.json file.');
  console.log('\nPlease ensure a valid package.json is in the root of this project\n');
  return;
}

packageJSON.cordovaPlugins = packageJSON.cordovaPlugins || [];
packageJSON.cordovaPlugins.forEach(function(plugin) {
  exec('cordova plugin add ' + plugin, function(error, stdout) {
    sys.puts(stdout);
  });
});
```

Here is a gist with the log files for each of the above build configurations. 

[Build config log files](https://gist.github.com/bmwertman/61d3d0092fc0c5eb36d04d37aa9efd50)

 Locally I have my ionic command line at v2.0.0 and my app has ionic v1.3.2 installed via Bower. Builds work as expected via `ionic run android` or `ionic build android`.

**Comment by dmitrii-snytkin** [comment]
Hello, @bmwertman . Thanks for reporting and sorry for delay.
I attempted to reproduce your case. I generated ionic v1 app with ionic-cli v 2.2.3 and I used cordova v6.4.0. My build script is following:
```
npm install
ionic hooks add  // fix this error https://forum.ionicframework.com/t/how-to-fix-this-error-spawn-eacces/20490/3
ionic platform add android
ionic build android
```

I have trouble with your hook script in my local machine, therefore i changed it:
```
#!/bin/bash
ionic state restore --plugins
```

It installs plugins too.
I have built the app successfully ([log](https://gist.github.com/dmitrii-snytkin/4fc1ea5b74d07a361aedafaa6c8a6906)). Can you try my solution?
