### ISSUE TITLE
Ionic commands do not stop build upon erroring

### ISSUE THREAD

**Issue by CookieCookson** [Microsoft/vsts-cordova-tasks#65]
Hey all, firstly I love this extension to bits! I have encountered a bit of an issue which I am hoping you could help with. I've started using the Ionic commands rather than the Cordova commands for my project, but it behaves slightly differently. When I do `cordova build ios` and it has a broken build.json file, it errors and stops the build with an error. However, when doing `ionic build ios`, it errors and carrys on with the build as if it was successful. This also happens on commands such as `ionic resources` which is less than ideal. Is this an issue with how ionic CLI returns commands or the VSTS extension?

See below for my log snippet:
```
=== BUILD TARGET elixel-ionic-template-app-v2 OF PROJECT elixel-ionic-template-app-v2 WITH CONFIGURATION Debug ===
Check dependencies
elixel-ionic-template-app-v2 requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'
** ARCHIVE FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/christiancook/myagent/_work/31/s/platforms/ios/cordova/build-debug.xcconfig,-workspace,elixel-ionic-template-app-v2.xcworkspace,-scheme,elixel-ionic-template-app-v2,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,elixel-ionic-template-app-v2.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/christiancook/myagent/_work/31/s/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/christiancook/myagent/_work/31/s/platforms/ios/build/sharedpch
******************************************************************************
Finishing: Ionic Command build ios
******************************************************************************

...Then goes on to other build commands, rather than throwing an error
```

**Comment by drewgillies** [comment]
This seems to be an Ionic bug (https://github.com/driftyco/ionic-cli/issues/1563) and we've decided to wait until it is fixed upstream.
