### ISSUE TITLE
Custom Build Configurations

### ISSUE THREAD

**Issue by jamesandersen** [Microsoft/vsts-cordova-tasks#67]
My cordova project has some custom iOS build configurations (for different environments) which each specify different bundle IDs, product names, etc.   When I enter one of these custom build configurations in the Configuration property of the Cordova Build task it appears to be ignored and `Debug` is used instead.
![image](https://cloud.githubusercontent.com/assets/2119576/25495689/59460886-2b3b-11e7-8dcf-0073b64dc24d.png)

I get an error which is expected because the wrong configuration was used... I include it here only because it shows that `Debug` was passed instead of `PluginTest` which is what I need in this scenario:
```
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/vso113131/vsts-agent/_work/8/s/app/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,MyApp.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/vso113131/vsts-agent/_work/8/s/app/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/vso113131/vsts-agent/_work/8/s/app/platforms/ios/build/sharedpch
```
Is there any way to force the use of a custom configuration that I've specified?

**Comment by dmitriy-petrishin** [comment]
Hi there.
If you still didn't figure out, please follow my instructions. Add new variable, for example "customConfig" with your custom configuration name "PluginTest"
<img width="1377" alt="screen shot 2017-06-05 at 6 42 20 pm" src="https://cloud.githubusercontent.com/assets/28645748/26791136/cdb4dbc8-4a1e-11e7-8042-9004cabf3734.png">

After, link that variable to configuration textbox.
<img width="772" alt="screen shot 2017-06-05 at 6 45 00 pm" src="https://cloud.githubusercontent.com/assets/28645748/26791249/219d3f5a-4a1f-11e7-9341-27d6dacc07fc.png">

Hope, that will help.

**Comment by jamesandersen** [comment]
@dmitriy-petrishin thanks for the response... we ended up doing a direct XCode build because of this issue but it's good information for future reference.

**Comment by dmitriy-petrishin** [comment]
@jamesandersen Sorry for late answer.
I will try to push the suggestion of writing new article about custom configurations because there are not enough information about that.

**Comment by dmitriy-petrishin** [comment]
@jamesandersen I'm gonna close that issue. 
So if there will be some problems feel free to reopen.
