### ISSUE TITLE
No agent could be found for xcode, npm

### ISSUE THREAD

**Issue by cocowalla** [Microsoft/vsts-cordova-tasks#75]
The [docs on building with Cordova](https://www.visualstudio.com/en-us/docs/build/apps/mobile/cordova-build) show how to setup a demand for `xcode` when building for iOS - but when attempting to queue the build I get this error:

`No agent could be found with the following capabilities: xcode, npm`

I've tried this with both the Hosted and Hosted VS2017 agents, with the same result.

**Comment by cocowalla** [comment]
My mistake - I thought VSO came with an OSX build agent as standard, but you need to bring your own. Disappointing, but that's how it is :(

**Comment by deepak10** [comment]
Did u resolve this issue and how?

**Comment by cocowalla** [comment]
@deepak10 I used a hosted MacOS server.

However, I believe Azure DevOps does now support hosted MacOS builds as standard, so the plan is to move away from the hosted server we use and use that instead.
