### ISSUE TITLE
Ionic command using its own version of npm

### ISSUE THREAD

**Issue by vivekdhami** [Microsoft/vsts-cordova-tasks#77]
I am using ionic command tasks from VSTS to build ionic apps for both ios and android. However it is always failing on the ionic command task with npm package installation failures.

The build runs on a private agent that has npm/3.10.10 and node/v6.11.2 in use. However ionic command task is still using npm 2.15.12. Would it be possible to use the preferred npm version with ionic command somehow?  

This is the information available from npm VSTS task: 
user-agent = "npm/3.10.10 node/v6.11.2 darwin x64"

This is the information from ionic command task using **ionic info** command:
  Node              : v6.11.2
    npm               : 2.15.12 
    OS                : macOS Sierra

**Comment by vivekdhami** [comment]
I am not using vsts-cordova-tasks as they were not working with ionic 3. Also I feel its much easier working with ionic builds using command line VSTS task instead and it gives you more control over the build process.

**Comment by cwoolum** [comment]
I'm running into this same issue. How did you end up solving it?
