### ISSUE TITLE
Ionic Cordova iOS Build Failed - Scheme not found

### ISSUE THREAD

**Issue by jln1989** [Microsoft/vsts-cordova-tasks#78]
Hi,

Am trying to use VSTS for Ionic2 iOS build and IPA file generation. The highlevel flow is given below which am using.

1. Get sources from VSTS Git & clean the previous build folders
2. NPM Install
3. Ionic platform add and Ionic Build
4. XCODE Build for IPA

The steps 1-3 are working fine without any issues but the step 4 is failing.

The error am getting is:

> xcodebuild: error: The project named "TestProject" does not contain a scheme named "TestProject". The "-list" option can be used to find the names of the schemes in the project

Is there any option to set the scheme while the VSTS tasks are being run? Please let me know as we are unable to proceed further.

**Comment by drewgillies** [comment]
This looks to be stagnant after 8 months, so I'll go ahead and close it. Any concerns, please let me know.
