### ISSUE TITLE
Cordova Build Agent Error - "CordovaError: Current working directory is not a Cordova-based project."

### ISSUE THREAD

**Issue by nknvtl** [Microsoft/vsts-cordova-tasks#83]
Hi, when I build my Cordova project, I am thrown an error that reads "_CordovaError: Current working directory is not a Cordova-based project._" Can you help, please? Log attached.

It is a Cordova project.

[logs_39.zip](https://github.com/Microsoft/vsts-cordova-tasks/files/1631947/logs_39.zip)

**Comment by SpartanVFL** [comment]
Probably not the proper way to fix this but I got the same error with an Ionic app. I had to run an Ionic command to create the iOS platform first (since I don't store the platforms in the repo) and then it would recognize it as a cordova project

**Comment by nknvtl** [comment]
What's the command you ran?

**Comment by chazguerrero** [comment]
from your logs it doesn't look like it can find your package.json file either. are you specifying the root directory of the Cordova project?

**Comment by drewgillies** [comment]
@nknvtl and @chazguerrero Can you comment on the status of this please? Is this still a break?

**Comment by drewgillies** [comment]
No response. Closing.
