### ISSUE TITLE
Arguments passed into "command" tasks do not properly handle spaces in quotes or escaped spaces

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-cordova-tasks#9]
Identical problem to...

https://github.com/Microsoft/vso-agent-tasks/issues/814

...and...

https://github.com/Microsoft/vso-agent-tasks/issues/804

Unless vso-task-lib is enhanced to use minimist instead of split for getDelimitedInput we should look at each use of that function in Cordova Build, Ionic Command, Cordova Command, and the upcoming PhoneGap and TACO CLI command tasks and switch to minimist in cases where we are processing a set of command line arguments instead of something like a comma separated list.

**Comment by bryanmacfarlane** [comment]
You're not supposed to use .getDelimitedInput.  See the comments in vso-task-lib

You should just call .arg with the string args - it will split properly on double quotes.  See the shellscript task

**Comment by bryanmacfarlane** [comment]
.getDelimitedInput is reserved for simple lists like targets

**Comment by Chuxel** [comment]
Perfect - Thanks Bryan, we'll get that fixed.

**Comment by bryanmacfarlane** [comment]
It's a very interesting idea to use minimist however.  We do a regex matching between double quotes.  I'm sure there's cases we miss ...

**Comment by bryanmacfarlane** [comment]
BTW, note sure if you saw my mail on 'statically linking' vso-task-lib into our tasks.  This means we can fix arg parsing and it will roll with the tasks (rather than dependening on folks to update their agents).  So, I'll look into minimist in lib

**Comment by Chuxel** [comment]
Yeah that's a good plan. The tasks in the vsts-cordova-tasks repo currently use package.json to pull in a number of modules including vso-task-lib (^4.5.0) under node_modules locally to the task which we then upload with the extension - so I think that should allow us to do update out of band now should it not?

**Comment by ryuyu** [comment]
I've submitted a pull request replacing the calls to getDelimitedInput (https://github.com/Microsoft/vsts-cordova-tasks/pull/10). Once i can confirm this is the correct approach, I will mirror this change in the new tasks that haven't been merged in yet.

**Comment by ryuyu** [comment]
Fixed with pull request https://github.com/Microsoft/vsts-cordova-tasks/pull/10
